### ISSUE TITLE
DShell compatibility issues with discord.py v2.0

### ISSUE THREAD

**Issue by seriaati** [ImNimboss/dshell#4]
```py
await bot.load_extension('dshell')
```
error: `TypeError: object NoneType can't be used in 'await' expression`

**Comment by ImNimboss** [comment]
This doesn't look like a dshell problem, it seems to be a problem in your code. Since I don't have the rest of your code (and I'm a little rusty in dpy 2.0), you may want to refer to [this link](https://stackoverflow.com/questions/56872323/typeerror-object-nonetype-cant-be-used-in-await-expression) or maybe your situation is similar to [this link](https://stackoverflow.com/questions/68457858/object-nonetype-cant-be-used-in-await-expression).

**Comment by seriaati** [comment]
No, it's a dshell problem.
I guess it's because you haven't updated it to dpy 2.0
Extension loadings are now async.
```py
\Programs\Python\Python310\lib\site-packages\dshell\cog.py:376: RuntimeWarning: coroutine 'BotBase.add_cog' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "C:\Users\seria\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 946, in _load_from_module_spec
    await setup(self)
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by ImNimboss** [comment]
Ahh right my bad, I'll get to it ASAP

**Comment by ImNimboss** [comment]
@seriaati Hiya, I've made the commits to make it compatible with v2.0. I scanned the breaking changes list and checked the docs so hopefully I haven't missed any. Try the new version by `pip install -U git+https://github.com/ImNimboss/dshell.git`?

If you face no further problems, I'll close the issue and publish the new version on PyPI.

**Comment by seriaati** [comment]
The cog loads, but it's not working.
I haven't used dshell before so I'm not sure if i'm settings it up correctly.
This is inside the bot's `setup_hook`:
```py
await self.load_extension("dshell")
self.dshell_config["shell_channels"] = [1015210645320388609]
```
After I load dshell I set the config.
When I go to the channel and type `pip freeze`, `git pull`, and `echo test`, nothing happens.
The bot has permission reading the channel.

**Comment by ImNimboss** [comment]
Ah I know this is high priority but d'you mind if I get to this after 21st September? That's when my exams end and there isn't any other maintainer for dshell

**Comment by ImNimboss** [comment]
Actually, what type of object is `self` here? The `dshell_config` attribute needs to be assigned to your bot object

**Comment by seriaati** [comment]
> Actually, what type of object is `self` here? The `dshell_config` attribute needs to be assigned to your bot object

`self` is a bot object

**Comment by seriaati** [comment]
> Ah I know this is high priority but d'you mind if I get to this after 21st September? That's when my exams end and there isn't any other maintainer for dshell

That's actually fine, I don't really use dshell as part of my workflow, but just faced the issue when I want to try it out.
take your time and good luck on your exam.

**Comment by ImNimboss** [comment]
Thanks :> So I ran the second example in Documentation/Examples.md and it worked perfectly. Any idea what's causing yours to not work while the basic template works?

**Comment by ImNimboss** [comment]
And I also ran this example with a `setup_hook` like yours has

```python
from discord.ext import commands
import asyncio, discord

class MyBot(commands.Bot):
    async def on_ready(self):
        print('Logged in')

    async def setup_hook(self):
        await self.load_extension('dshell')
        self.dshell_config['shell_channels'] = [1022487485323956244]
        self.dshell_config['shell_in_dms'] = True

bot = MyBot(command_prefix = 's!', intents = discord.Intents.all())
bot.run(TOKEN)
```

It worked perfectly for me, maybe it's another problem like ratelimits, permissions, ...?

(Also I used windows for testing but I don't think that should matter)

**Comment by seriaati** [comment]
I tried with the following two scenarios:
```py
self.dshell_config['shell_in_dms'] = True
```
Works, I can use shell in bot's DM
```py
self.dshell_config['shell_channels'] = [channel_id]
```
Doesn't work in the channel specified

**Comment by ImNimboss** [comment]
In that case, I doubt it could be the library's problem. It can read shell commands and there's no code prohibiting channel reading anywhere. 

Try:
* _Checking channel permissions, intents_, other config etc. for the bot. If channel perms are too convoluted then you could use a fresh channel in a testing server (if you aren't already).
* Keep in mind dshell requires the messages intent since it's directly reading message content from a channel.
* If your bot is verified/can't get the message intent, that would explain why it can only detect DM shell commands. Try mentioning the bot in your shell command somehow - if it responds on mentioning then you probably have a message intent problem on your hands. 
* Check whether it's having ratelimit problems in channel messages using dpy's logging.
* I guess if all that doesn't work a quick reinstall from git wouldn't hurt.
* Unless there's anything I missed, last option is to poke around the library's internals and use debuggers/print statements but hopefully we don't have to do that.

While you do that, I'll crosscheck again if there's something wrong with the library.

**Comment by seriaati** [comment]
yeah I forgot that my bot doesn't have the message intent enabled

**Comment by ImNimboss** [comment]
Alright, I'll release this version to PyPI. Thanks for bringing the compatibility issue to my attention :>
